### ISSUE TITLE
Create database to store raw extracted data from phish.net 

### ISSUE THREAD

**Issue by andrewrreed** [areed1242/phish-setlist-prediction#4]

**Comment by mikearango** [comment]
- [x] Create DB in US East region
  - Free RDS Tier
- [ ] Set up security group so Mike and Andrew can access
- [ ] Send out master DB Credentials

**Comment by mikearango** [comment]
- [x] Create free RDS Tier PostgreSQL Database 
<img width="1038" alt="Screen Shot 2019-04-19 at 6 31 59 PM" src="https://user-images.githubusercontent.com/25807316/56446579-6e510080-62d1-11e9-87fe-12ad2976f041.png">

- [x] Open to all traffic
  - Lock it down later when we need to
- [x] Test DB connection 
    - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToPostgreSQLInstance.html
<img width="244" alt="Screen Shot 2019-04-19 at 6 52 03 PM" src="https://user-images.githubusercontent.com/25807316/56447073-42834a00-62d4-11e9-91e4-63341822c0fc.png">

- [x] Send credentials to Andrew
